[package]
name = "mashiro-task"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
comfy-table = "7.1.1"
home = "0.5.9"
rand = "0.8.5"
regex = "1.11.0"
